Sapper_task5/Sapper_task5/Models/Sapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sapper_task5.Models
{
    public class Sapper
    {
        public int Width
        { get; set; }

        public int Height
        { get; set; }

        public int NumberOfMine
        { get; set; }
        public bool IsTimeLimit
        {
            get
            {
                return TimeLimit.Ticks > 0;
            }
        }
        public TimeSpan TimeLimit
        { get; set; }


    }
}

Sapper_task5/Sapper_task5/Models/SapperEngineModel.cs
using System.Collections.Generic;
using Newtonsoft.Json;
using Sapper_task5.Sapper_Engine;

namespace Sapper_task5.Models
{
    public class SapperEngineModel
    {
        [JsonIgnore]
        public static readonly Dictionary<CellTypeInGame, string> CellTypeNames = new Dictionary<CellTypeInGame, string>()
        {
            {CellTypeInGame.NearMine, "NearMine"},
            {CellTypeInGame.Mine, "Mine"},
            {CellTypeInGame.Free, "Free"}

        };
        
         [JsonIgnore]
         public static readonly Dictionary<CellTypeForUser, string> CellTypeForNamesUser= new Dictionary<CellTypeForUser, string>()
        {
            {CellTypeForUser.IsFlag, "IsFlag"},
            {CellTypeForUser.Hide, "Hide"}
        };

         
        [JsonIgnore]
        public static readonly Dictionary<GameState, string> GameStateNames = new Dictionary<GameState, string>()
        {
            {GameState.Game , "Game"},
            {GameState.Victory, "Victory"},
            {GameState.GameOver, "Gameover"}
        }; 
        
        public string[][] Matrix { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }              
        public string State { get; set; }
        public long EndTime { get; set; }            
    }

}

Sapper_task5/Sapper_task5/Models/UserActionModel.cs
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Sapper_task5.Models
{
    public class UserActionModel
    {
        public enum ActionEnum
        {
            Left,
            Right,          
            Invalid
        }

        [JsonIgnore]
        public static readonly Dictionary<string,ActionEnum > ActionNames = new Dictionary<string, ActionEnum>()
        {
            {"left",ActionEnum.Left },
            {"right",ActionEnum.Right}
        };
        [JsonIgnore]
        public ActionEnum Action
        {
            get
            {
                return ActionNames.ContainsKey(ActionName) ? ActionNames[ActionName] : ActionEnum.Invalid;
            }
        }
        public string ActionName { get; set; }
        public int Col { get; set; }
        public int Row { get; set; }

    }
}

Sapper_task5/Sapper_task5/Controllers/HomeController.cs
using System.Web.Mvc;
namespace Sapper_task5.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return Redirect("Sapper/Create");
        }    
    }
}

Sapper_task5/Sapper_task5/Controllers/SapperController.cs
using System;
using System.Web.Mvc;
using Newtonsoft.Json;
using  Sapper_task5.Models;
using  Sapper_task5.Sapper_Engine;

namespace Sapper_task5.Controllers
{
  public class SapperController : Controller
    {

        private SapperEngine Game
        {
            get
            {
                return (SapperEngine)Session["game"];
            }
            set
            {
                Session.Add("game", value);
            }
        }

        private Sapper sapper
        {
            get
            {
                return (Sapper)Session["sapper"];
            }
            set
            {
                Session.Add("sapper", value);
            }
        }

      //  private Sapper sapper;
        
        
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Sapper _sapper)
        {
            bool error = false;
            int _width=0;
            int _height=0;
            int _mine=0;
            sapper = _sapper;  
            TimeSpan _time; 
            _time = TimeSpan.Zero;
            try
            {
                 _width = sapper.Width;
                 _height = sapper.Height;
                 _mine = sapper.NumberOfMine;
                _time = sapper.TimeLimit;
                if (_width < 1 || _width > 100)
                    error = true;
                if (_height < 1 || _height > 100)
                    error = true;
                if (_mine < 1 || _mine > _width * _height - (_width * _height)/50)
                    error = true;       
            }
            catch (Exception e)
            {
                error = true;
                ViewBag.Result = (e);
            }
            if (error)
                ViewBag.Result += ("Invalid settings!");
            else
            {
                ViewBag.Result = "";
                Game=new SapperEngine();
                Game.SapperCreate(_width, _height, _mine, DateTime.Now + _time);               
            }
            return View();
        }

        [HttpPost]
        public void GetGameState()
        {
            try
            {
                if (Game.GetGameState == GameState.GameOver)
                Game.OpenAllMines();
                var model = GetModel();
                var jsonObject = JsonConvert.SerializeObject(model);
                Response.Write(jsonObject);
            }
            catch (Exception)
            {
                Response.Write("null");
            }           
        }

        public SapperEngineModel GetModel()
      {
            Cell[,] _matrix;
           _matrix = Game.GetGameMatrix();
          var matrix = new string[sapper.Height][];
          for (int i = 0; i < sapper.Height; i++)
          {
              matrix[i] = new string[sapper.Width];
              for (int j = 0; j < sapper.Width; j++)
              {
                  if (_matrix[j, i].IsFlag)
                  {
                      matrix[i][j] = SapperEngineModel.CellTypeForNamesUser[CellTypeForUser.IsFlag];
                      continue;
                  }
                  if (_matrix[j, i].Hide)
                  {
                      matrix[i][j] = SapperEngineModel.CellTypeForNamesUser[CellTypeForUser.Hide];
                  }
                  else
                  {
                      if (_matrix[j, i].Type == CellTypeInGame.Mine)
                      {
                          matrix[i][j] = SapperEngineModel.CellTypeNames[CellTypeInGame.Mine];
                          continue;
                      }
                      if (_matrix[j, i].Type == CellTypeInGame.NearMine)
                      {
                          matrix[i][j] = _matrix[j, i].NumberOfMine.ToString();
                          continue;
                      }
                      if (_matrix[j, i].Type == CellTypeInGame.Free)
                      {
                          matrix[i][j] = SapperEngineModel.CellTypeNames[CellTypeInGame.Free];                         
                      }
                  }
              }
          }
            DateTime _endTime;
            _endTime = Game.GetTimerActivStat ? Game.GetEndTime : DateTime.MaxValue;          
            var model = new SapperEngineModel
            {             
                Matrix = matrix,
                Width = sapper.Width,
                Height = sapper.Height,
                State = SapperEngineModel.GameStateNames[Game.GetGameState],
                EndTime = ((_endTime.Ticks - new DateTime(1970, 1, 1, 3, 0, 0).Ticks) / 10000)               
            };
            return model;         
      }


      [HttpPost]
        public void UserAction()
      {
          try
          {
               var userAction = new UserActionModel
               {
                  ActionName = Request.Form["ActionName"],
                  Col = Convert.ToInt32(Request.Form["Col"]),
                  Row = Convert.ToInt32(Request.Form["Row"]),
              };
               if (Game.IsNewGeme)
               Game.NewGame(userAction.Col, userAction.Row);
              if (Game.GetGameState != GameState.Game)
              {
                  GetGameState();
                  return;
              }            
              if (userAction.Action == UserActionModel.ActionEnum.Left)
                  Game.ClickCell(userAction.Row, userAction.Col, Click.Left);

              if (userAction.Action == UserActionModel.ActionEnum.Right)
                  Game.ClickCell(userAction.Row, userAction.Col, Click.Right);

              GetGameState();
          }
          catch (Exception)
          {
              return;            
          }       
      }


    }

}

Sapper_task5/Sapper_task5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Sapper Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sapper</h2>
<div>
    <a href="@Url.Action("Create", "Sapper")">Start new game</a><br />
</div>

Sapper_task5/Sapper_task5/Views/Sapper/Create.cshtml
@model Sapper_task5.Models.Sapper
@{
    ViewBag.Title = "Sapper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create new game</h2>
<div>
    <a href="@Url.Action("Index", "Home")">Back</a>
    <br />
<br />
    </div>
<div>
@using (Html.BeginForm("Create", "Sapper", FormMethod.Post))
            {
                <div>
                    @Html.ValidationMessage("Error")
                </div>
                <label>Width (1-100)</label>
                <div>        
                    @Html.TextBox("Width",10)
                </div>
                <label>Height (1-100)</label>
                <div>
                    @Html.TextBox("Height", 10)
                </div>
                <label>Mine Number</label>
                <div>
                    @Html.TextBox("NumberOfMine", 10)
                </div>
                <label>Time Limit (00:00:00 means unlimited time)</label>
                <div>
                    @Html.TextBox("TimeLimit","00:00:00")
                </div>
                   <h4>Instruction</h4>
                   <ul>
                       <li>Left Mouse Click (LMC) - open a cell.</li>
                       <li>Ctrl+LMC - toggle a flag; open 8 cells around except numeric.</li>
                   </ul>
                <div>
                    <input type="submit" onclick="init()"  value="Create"/>
                </div>
                if (!string.IsNullOrWhiteSpace(ViewBag.Result))
                {
                    <p>@ViewBag.Result</p> 
                }
                else
                {
                    <br />
                    Html.RenderPartial("Game");
                }
            }
        </div>  
<div>
    
    

</div>

Sapper_task5/Sapper_task5/Views/Sapper/Game.cshtml
<div class="sapper-content">
    <div class="sapper-message">
    </div>
    <div class="sapper-time">
    </div>
    <div class="sapper-area">
    </div>
</div>
@Scripts.Render("~/bundles/sapper-modul")

Sapper_task5/Sapper_task5/Views/Sapper/Index.cshtml
@{
    ViewBag.Title = "Sapper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sapper</h2>
<div>
    <a href="@Url.Action("Back", "Sapper")">Back</a><br />
    <a href="@Url.Action("Reload", "Sapper")">Reload</a>
    <h4>Instruction</h4>
    <ul>
        <li>Left Mouse Click (LMC) - open a cell.</li>
        <li>Ctrl+LMC - toggle a flag.</li>
        <li>Alt+LMC - open 8 cells around except flagged.</li>
    </ul>
    <br />
    @{Html.RenderPartial("Game");}
</div>

Sapper_task5/Sapper_task5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
     @Scripts.Render("~/bundles/jquery")
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>